Name: Frontend Service
Description: The frontend service
Author: jan gehring <jan.gehring@gmail.com>
License: Apache 2.0
Requires:
  Rex::Ext::ParamLookup:
    git: https://bitbucket.org/jfried/rex-ext-paramlookup.git
    branch: master
  Rex::NTP::Base:
    git: https://bitbucket.org/jfried/rex-ntp-base.git
    branch: master
  Rex::OS::Base:
    git: https://bitbucket.org/jfried/rex-os-base.git
    branch: master
