Name: Frontend Service
Description: The frontend service
Author: jan gehring <jan.gehring@gmail.com>
License: Apache 2.0
Require:
  Rex::NTP::Base:
    git: https://github.com/krimdomu/rex-ntp-base.git
    branch: master
  Rex::OS::Base:
    git: https://github.com/krimdomu/rex-os-base.git
    branch: master
# PerlRequires:
#   Net::SSH2:
#     git: https://github.com/rkitover/net-ssh2.git
#     branch: master
